Fix premature end block in default Prometheus CR
When prometheus.enabled=false, the current chart fails to render the manifest since anything that comes after the premature end block is not excluded. As a result, we get the following error on install when trying to validate the created manifest:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [apiVersion not set, kind not set]
```

This error also exists in upstream:
https://github.com/prometheus-community/helm-charts/blob/5dc19ca22e6038b98c03e77df4d9b313b642acdb/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L264-L265